### ISSUE TITLE
LCD Connector is Mirrored

### ISSUE THREAD

**Issue by aperley** [WiseLabCMU/gridballast#5]
The LCD ribbon cable connector is wired the wrong way around. The exposed end of the ribbon cable should be inserted into the connector facing up, but the wiring of the pins requires that it be inserted facing down. This does not make a great connection and requires that the locking plastic piece be inserted above the ribbon cable instead of below it.

**Comment by linux4life798** [comment]
We now use the connector found [here](https://www.digikey.com/products/en?keywords=HFY031CT-ND).

@anhluong Added the footprint to the PCB.
